cc_binary(
    name = "slist_test",
    srcs = ["slist_test.c"],
    deps = [
        "//lib:slist",
    ],
)
cc_binary(
    name = "stack_test",
    srcs = ["stack_test.c"],
    deps = [
        "//lib:stack",
        "//lib:slist",
    ],
)
cc_binary(
    name = "queue_test",
    srcs = ["queue_test.c"],
    deps = [
        "//lib:queue",
        "//lib:slist",
    ],
)
cc_binary(
    name = "qsort",
    srcs = ["qsort.c"],
    deps = [
        "//lib:stack",
        "//lib:slist",
    ],
)
cc_binary(
    name = "tree1",
    srcs = ["tree1.c"],
)
